version: 2
jobs:
  build:
    working_directory: ~/tmp

    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    steps:
      - checkout
      - run: npm install
  test:
      - run:
          name: sample_testing
          command: |
            echo "hi there!"
